### ISSUE TITLE
Notify when no tldr entries are available

### ISSUE THREAD

**Issue by jandamm** [mrjones2014/tldr.nvim#4]
This is not really an issue of your plugin but it may be nice if you'd improve this handling.

I just installed `tealdeer` and your plugin. When I tried `:Tldr` in nvim it did not work without any message.
When I then tried `tldr` in the shell it didn't work either and told me that the cache is empty and to run `tldr --update`.

Maybe you could use `vim.notify` to show a message when `tldr` does not provide any entries. So it's clear that it isn't an issue with your plugin but with the `tldr` command itself.

**Comment by mrjones2014** [comment]
This should be doable.

**Comment by mrjones2014** [comment]
@jandamm fixed.

**Comment by jandamm** [comment]
Nice, works as expected.
I'm just a bit confused that I didn't get an error message before. I checked `:messages` but there wasn't anything logged 🤷

**Comment by mrjones2014** [comment]
I think it has to do with the way I was using `vim.api.nvim_err_writeln` before. I think somehow the message gets lost across the Lua/Vimscript boundary or something. Not sure exactly.

But it's using `vim.notify` now which works.
